# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Helper function for performing a weighted Kolmogorov-Smirnov-like procedure.
#' @param gex numeric: normalized gene expression values
#' @param gss list: indices of genes in each gene set
#' @param mus numeric: means of all genes
#' @param sds numeric: standard deviations of all genes
#' @returns Modified Kuiper statistic (sum of minimal and maximal deviations during running sum)
wks <- function(gex, gss, mus, sds) {
  .Call(`_Seqtometry_wks`, gex, gss, mus, sds)
}
