# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Helper function for performing a weighted Kolmogorov-Smirnov like procedure.
#' @param gene_ranks numeric: centered gene expression ranks
#' @param sig_idx numeric: indices of genes belonging to the signature (gene set) being scored
#' @param aux numeric: two element vector containing 
#'   0. Centering value that was used for ranks
#'   1. Start index (after centering) for the running sum procedure
#' @returns Modified Kuiper statistic (sum of minimal and maximal deviations during running sum)
wks <- function(gene_ranks, sig_idx, aux) {
    .Call(`_Seqtometry_wks`, gene_ranks, sig_idx, aux)
}

